# Generated by Django 5.2.9 on 2025-12-24 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('photo', models.ImageField(upload_to='criminal_photos/')),
                ('crime_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_date', models.DateField()),
                ('crime_location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_database.criminal')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_file', models.FileField(upload_to='evidence_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('crime_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_database.crimerecord')),
            ],
        ),
    ]
