# Generated by Django 5.2.9 on 2026-01-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal',
            name='face_label',
            field=models.CharField(default='unknown', help_text='Must match dataset folder name (e.g., person_001)', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
