# Generated by Django 5.2.9 on 2026-01-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_database', '0002_criminal_face_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_label', models.CharField(max_length=50)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
