# Generated by Django 5.2.9 on 2026-02-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_database', '0006_crimerecord_crime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertlog',
            name='snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='alert_snapshots/'),
        ),
    ]
